self.STR = self.STR || new Proxy(
	{
		LANGUAGE: document.documentElement.getAttribute("lang"),
		"en-US": {
			userBlock: "Block",
			avatarBlock: "Block avatar",
			signatureBlock: "Block signature",
			userUnblock: "-",
			avatarUnblock: "Unblock avatar",
			signatureUnblock: "Unblock signature",
			reaction: "Like",
			reactionName: {
				techolay: {
					1: "Like",
					2: "Wonderful",
					3: "Hahaha",
					4: "Wow",
					5: "Sad",
					6: "Rage",
					7: "Dislike",
					8: "Thinking",
					9: "Love",
					10: "o7",
					11: "No Comment",
					12: "What?",
					13: "Clap",
					14: "Sherlock",
					15: "Whoa",
					16: "Cool",
					17: "Wink",
					18: "Flushed",
					19: "Yeeey",
					20: "Ayy",
					21: ":')",
					22: "Şşşt..",
					23: "Eridimm",
					24: "Offf!",
				},
				technopat: {
					1: "Like",
					2: "Splendid",
					3: "Hahaha",
					4: "Incredible",
					5: "Upset",
					6: "Angry",
					7: "Let me think",
					8: "Dislike",
				},
			},
			reactionYou: "You, ",
			report: "Report",
			actionBarMenu: "More options",
			combinedTabConjunction: " and",
			save: "Save",
			addNote: "Add note",
			noteSavedMessage: "Note has been saved.",
			report: "Report",
			find: "Find",
			findContent: "Find content",
			findAllContentBy: userName => `Find all content by ${ userName }`,
			findAllThreadsBy: userName => `Find all threads by ${ userName }`,
		},
		"tr-TR": {
			userBlock: "Engelle",
			avatarBlock: "Avatar engelle",
			signatureBlock: "İmza engelle",
			userUnblock: "-",
			avatarUnblock: "Avatarı göster",
			signatureUnblock: "İmzayı göster",
			reaction: {
				techolay: "Beğendim",
				technopat: "Beğen",
			},
			reactionName: {
				techolay: {
					1: "Beğendim",
					2: "Muhteşem",
					3: "Hahaha",
					4: "İnanılmaz",
					5: "Üzgün",
					6: "Kızgın",
					7: "Beğenmedim",
					8: "Düşündürücü",
					9: "Kalp",
					10: "o7",
					11: "Yorum Yok",
					12: "Ney?",
					13: "Bravo!",
					14: "Sherlock",
					15: "Vaaaay...",
					16: "Havalı",
					17: "Kııppss",
					18: "Ayıp",
					19: "Yeeey",
					20: "Ayy",
					21: ":')",
					22: "Şşşt..",
					23: "Eridimm",
					24: "Offf!",
				},
				technopat: {
					1: "Beğen",
					2: "Muhteşem",
					3: "Hahaha",
					4: "İnanılmaz",
					5: "Üzgün",
					6: "Kızgın",
					7: "Düşündürücü",
					8: "Beğenmedim",
				},
			},
			reactionYou: "Siz, ",
			report: "Rapor",
			actionBarMenu: "Detaylar",
			combinedTabConjunction: " ve",
			save: "Kaydet",
			addNote: "Not ekle",
			noteSavedMessage: "Not kaydedildi.",
			report: "Rapor",
			find: "Bul",
			findContent: "İçerik bul",
			findAllContentBy: userName => `${ userName } tarafından gönderilen tüm içeriği arattır`,
			findAllThreadsBy: userName => `${ userName } tarafından açılan tüm konuları arattır`,
		},
	},
	{
		get(target, prop) {
			const value = target[target.LANGUAGE]?.[prop]?.[forum] ?? target[target.LANGUAGE]?.[prop];
			return typeof value === "function" ? value.bind(target) : value;
		},
	},
);
