name: Release

run-name: Release ${{ github.ref_name }}

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

env:
  CHROME_NAME: ${{ github.event.repository.name }}_${{ github.ref_name }}_chrome.crx
  FIREFOX_NAME: ${{ github.event.repository.name }}_${{ github.ref_name }}_firefox.xpi

jobs:
  chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Pack Extension
        run: |
          echo "${{ secrets.CHROME_PRIVATE_KEY_B64 }}" \
            | base64 --decode \
            > ../${{ github.event.repository.name }}.pem
          google-chrome \
            --pack-extension="${{ github.workspace }}" \
            --pack-extension-key="${{ github.workspace }}.pem"

      - name: Submit to Store
        run: npx chrome-webstore-upload-cli@next --source ${{ github.workspace }}.crx
        env:
          PUBLISHER_ID: ${{ secrets.CHROME_PUBLISHER_ID }}
          EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}

      - name: Rename Artifact
        run: mv ../*.crx ./${{ env.CHROME_NAME }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          archive: false
          retention-days: 1
          compression-level: 0
          if-no-files-found: error
          path: ${{ env.CHROME_NAME }}

  firefox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Generate manifest.json
        run: echo "$(jq -n -S -f manifest.jq)" > ../manifest.json
        working-directory: .manifest

      - name: Submit to Store
        run: npx web-ext@^9 sign
        env:
          WEB_EXT_API_KEY: ${{ secrets.FIREFOX_JWT_ISSUER }}
          WEB_EXT_API_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
          WEB_EXT_CHANNEL: listed
          WEB_EXT_APPROVAL_TIMEOUT: 3600000

      - name: Rename Artifact
        run: mv *.xpi ${{ env.FIREFOX_NAME }}
        working-directory: web-ext-artifacts

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          archive: false
          retention-days: 1
          compression-level: 0
          if-no-files-found: error
          path: web-ext-artifacts/${{ env.FIREFOX_NAME }}

  release:
    needs: [chrome, firefox]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true

      - name: Publish Release
        run: |
          gh release new ${{ github.ref_name }} \
            -t ${{ github.ref_name }} \
            --notes-from-tag \
            ${{ env.CHROME_NAME }} \
            ${{ env.FIREFOX_NAME }}
        env:
          GH_TOKEN: ${{ github.token }}
